websites:
  capital:
    name: 'Capital'
    url: 'https://www.capital.fr/'
    regex:
      watch:
      - 'http://www\.capital\.fr'
      - 'pmdstatic\.net'
      - 'prismaconnect\.fr'
      ignore:
        - 'http://www\.capital\.fr/assets/css/commons\.css'
