websites:
  - name: 'Capital'
    url: 'https://www.capital.fr/'
    regex:
      watch:
      - 'capital\.fr'
      - 'pmdstatic\.net'
      ignore:
        - 'http://www\.capital\.fr/assets/css/commons\.css'
