AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Pagespeed Monitoring
    Sam template for Pagespeed Monitoring

Globals:
    Function:
        Timeout: 180

Resources:

    DispatcherFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: dist/
            Handler: dispatcher.handler
            Runtime: python3.6
#            Environment:
#              Variables:
#                PAGESPEED_KEY: test
            Events:
                HelloWorld:
                    Type: Schedule
                    Properties:
                        Schedule: rate(1 second)

Outputs:

    DispatcherFunction:
      Description: "Hello World Lambda Function ARN"
      Value: !GetAtt HelloWorldFunction.Arn

    DispatcherFunctionIamRole:
      Description: "Implicit IAM Role created for Hello World function"
      Value: !GetAtt HelloWorldFunctionRole.Arn
